global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "devstack_local_db_exporter"
    static_configs:
      - targets: [localhost:9187]

  - job_name: "brawney_local"
    static_configs:
      - targets: ["localhost:9005"]
