{
 "title": "Brawney API",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(request_total[5m])*1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    { "expr": "request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri, method) (uri_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(uri, instance) (uri_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests (200) by uri",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by(uri) (uri_request_total{code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request failures by uri",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(uri_request_total{code!=\"200\"}[5m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (request_duration_sum) / sum(request_duration_count)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Request average by uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(request_duration_bucket[5m])) by (le, uri))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}