apiVersion: v1
kind: Namespace
metadata:
  name: proxy-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: proxy-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: proxy-prod
spec:
  ports:
    - name: http-server
      port: 80
      targetPort: 80
  selector:
    app: proxy
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy
  namespace: proxy-prod
spec:
  ingressClassName: nginx
  rules:
    - host: bolanos.dev
      http:
        paths:
          - backend:
              service:
                name: proxy-service
                port:
                  number: 80
            path: /
            pathType: Prefix
