apiVersion: v1
kind: Namespace
metadata:
  name: grafana-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-2-c8ec1c99
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      name: grafana-deployment
      namespace: grafana-prod
    spec:
      containers:
        - image: grafana/grafana
          imagePullPolicy: Always
          name: grafana
          ports:
            - containerPort: 3000
              name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: grafana-prod
spec:
  ports:
    - name: http-server
      port: 80
      targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: grafana-prod
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.bolanos.dev
      http:
        paths:
          - backend:
              service:
                name: grafana-service
                port:
                  number: 3000
            path: /
            pathType: Prefix
