apiVersion: v1
kind: Namespace
metadata:
  name: jaeger-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-2-c8e96a3a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
      name: jaeger-deployment
      namespace: jaeger-prod
    spec:
      containers:
        - image: jaegertracing/jaeger:2.5.0
          imagePullPolicy: Always
          name: jaeger
          ports:
            - containerPort: 16686
              name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: jaeger-prod
spec:
  ports:
    - name: http-server
      port: 80
      targetPort: 16686
    - name: dial-server
      port: 4317
      targetPort: 4317
  selector:
    app: jaeger
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: jaeger-prod
spec:
  ingressClassName: nginx
  rules:
    - host: jaeger.bolanos.dev
      http:
        paths:
          - backend:
              service:
                name: jaeger-service
                port:
                  number: 16686
            path: /
            pathType: Prefix
